### ISSUE TITLE
cann't userd in postgresql 9.6 ? 

### ISSUE THREAD

**Issue by digoal** [postgrespro/pg_query_state#1]
HI,
   I compile this contrib into postgresql 9.6, but when create extension pg_query_state, postgres crashed.
   
 step :  
```
   git clone ...
   git checkout PGPRO9_6
   patch postgresql9.6 with custom_signals.patch 
   patch postgresql9.6 with runtime_explain.patch
   recompile postgresql9.6
   compile pg_query_state 
   modify postgresql.conf 
      shared_preload_libraries = 'pg_query_state,pg_pathman,pg_stat_statements'
   restart database
   psql -c create extension pg_query_state, then crashed
```

```
CentOS 6.x x64
gcc 4.8.2
```

best regards,
digoal

**Comment by maksm90** [comment]
Hi, @digoal!

Thanks for extension testing!

I tried to reproduce your crash but failed to do it. Could you show the last server log messages especially those tagged with TRAP, LOG, DETAIL triples.

**Comment by digoal** [comment]
HI, 
  this is the core dump bt content.

```
(gdb) bt
#0  0x00007ffc212748a5 in raise () from /lib64/libc.so.6
#1  0x00007ffc21276085 in abort () from /lib64/libc.so.6
#2  0x000000000080a9c7 in ExceptionalCondition (conditionName=Unhandled dwarf expression opcode 0xf3
) at assert.c:54
#3  0x000000000062a2ac in lcons (datum=0xfbd8c0, list=0xf67570) at list.c:261
#4  0x00007ffc1b1ad983 in qs_ExecutorStart (queryDesc=0xfbd8c0, eflags=0) at pg_query_state.c:290
#5  0x0000000000614fb8 in _SPI_pquery (plan=0xf795d8, paramLI=0x0, snapshot=0x0, crosscheck_snapshot=0x0, read_only=0 '\000', fire_triggers=1 '\001', tcount=1) at spi.c:2410
#6  _SPI_execute_plan (plan=0xf795d8, paramLI=0x0, snapshot=0x0, crosscheck_snapshot=0x0, read_only=0 '\000', fire_triggers=1 '\001', tcount=1) at spi.c:2188
#7  0x00000000006153bd in SPI_execute_plan_with_paramlist (plan=0xf795d8, params=0x0, read_only=Unhandled dwarf expression opcode 0xf3
) at spi.c:446
#8  0x00007fe4c90273d1 in exec_stmt_execsql (estate=0x7fff4ee96520, stmt=0xf3a738) at pl_exec.c:3515
#9  0x00007fe4c9028de8 in exec_stmt (estate=0x7fff4ee96520, stmts=Unhandled dwarf expression opcode 0xf3
) at pl_exec.c:1503
#10 exec_stmts (estate=0x7fff4ee96520, stmts=Unhandled dwarf expression opcode 0xf3
) at pl_exec.c:1398
#11 0x00007fe4c902ab68 in exec_stmt_block (estate=0x7fff4ee96520, block=0xf3c118) at pl_exec.c:1306
#12 0x00007fe4c9028ac7 in exec_stmt (estate=0x7fff4ee96520, stmts=Unhandled dwarf expression opcode 0xf3
) at pl_exec.c:1431
#13 exec_stmts (estate=0x7fff4ee96520, stmts=Unhandled dwarf expression opcode 0xf3
) at pl_exec.c:1398
#14 0x00007fe4c902aef8 in exec_stmt_block (estate=0x7fff4ee96520, block=0xf3c170) at pl_exec.c:1336
#15 0x00007fe4c902be7a in plpgsql_exec_event_trigger (func=0xee2b98, trigdata=0x7fff4ee96bc0) at pl_exec.c:896
#16 0x00007fe4c901f2d7 in plpgsql_call_handler (fcinfo=0x7fff4ee967d0) at pl_handler.c:250
#17 0x0000000000591319 in EventTriggerInvoke (fn_oid_list=Unhandled dwarf expression opcode 0xf3
) at event_trigger.c:1052
#18 0x0000000000592065 in EventTriggerDDLCommandEnd (parsetree=Unhandled dwarf expression opcode 0xf3
) at event_trigger.c:850
#19 0x00000000007129f7 in ProcessUtilitySlow (parsetree=0xf122c0, 
    queryString=0xf0ade8 "-- complain if script is sourced in psql, rather than via CREATE EXTENSION\n\n\nCREATE FUNCTION pg_query_state(pid \t\tinteger\n\t\t\t\t\t\t\t , verbose\tboolean = FALSE\n\t\t\t\t\t\t\t , costs \tboolean = FALSE\n\t\t\t\t\t\t\t , t"..., context=Unhandled dwarf expression opcode 0xf3
) at utility.c:1564
#20 0x00000000007110b1 in standard_ProcessUtility (parsetree=0xf122c0, 
    queryString=0xf0ade8 "-- complain if script is sourced in psql, rather than via CREATE EXTENSION\n\n\nCREATE FUNCTION pg_query_state(pid \t\tinteger\n\t\t\t\t\t\t\t , verbose\tboolean = FALSE\n\t\t\t\t\t\t\t , costs \tboolean = FALSE\n\t\t\t\t\t\t\t , t"..., context=Unhandled dwarf expression opcode 0xf3
) at utility.c:907
#21 0x000000000059ac5d in execute_sql_string (extensionOid=Unhandled dwarf expression opcode 0xf3
) at extension.c:746
#22 execute_extension_script (extensionOid=Unhandled dwarf expression opcode 0xf3
) at extension.c:906
#23 0x000000000059bc78 in CreateExtensionInternal (parents=Unhandled dwarf expression opcode 0xf3
) at extension.c:1498
#24 0x000000000059c1e8 in CreateExtension (stmt=0xebf318) at extension.c:1556
#25 0x0000000000711d5c in ProcessUtilitySlow (parsetree=0xebf318, queryString=0xebe898 "create extension pg_query_state ;", context=Unhandled dwarf expression opcode 0xf3
) at utility.c:1296
#26 0x00000000007110b1 in standard_ProcessUtility (parsetree=0xebf318, queryString=0xebe898 "create extension pg_query_state ;", context=Unhandled dwarf expression opcode 0xf3
) at utility.c:907
#27 0x000000000070e418 in PortalRunUtility (portal=0xe471e8, utilityStmt=0xebf318, isTopLevel=Unhandled dwarf expression opcode 0xf3
) at pquery.c:1193
#28 0x000000000070efcd in PortalRunMulti (portal=0xe471e8, isTopLevel=1 '\001', setHoldSnapshot=0 '\000', dest=0xebf6a0, altdest=0xebf6a0, completionTag=0x7fff4ee97820 "") at pquery.c:1349
#29 0x000000000070fca3 in PortalRun (portal=0xe471e8, count=9223372036854775807, isTopLevel=Unhandled dwarf expression opcode 0xf3
) at pquery.c:815
#30 0x000000000070d74b in exec_simple_query (argc=Unhandled dwarf expression opcode 0xf3
) at postgres.c:1094
#31 PostgresMain (argc=Unhandled dwarf expression opcode 0xf3
) at postgres.c:4072
#32 0x000000000046b959 in BackendRun () at postmaster.c:4270
#33 BackendStartup () at postmaster.c:3944
#34 ServerLoop () at postmaster.c:1701
#35 0x00000000006a4f5d in PostmasterMain (argc=1, argv=Unhandled dwarf expression opcode 0xf3
) at postmaster.c:1309
#36 0x000000000046c83c in main (argc=1, argv=0xe27b50) at main.c:228
```

best regards,
digoal

**Comment by digoal** [comment]
I think it's my event trigger's problem.
sorry.

**Comment by digoal** [comment]
```
CREATE OR REPLACE FUNCTION public.ef_alter()
 RETURNS event_trigger
 LANGUAGE plpgsql
 STRICT
AS $function$  
declare  
  rec hstore;  
  v1 int8;  
  v2 oid;  
  v3 text;  
  v4 text;  
  v5 text;  
  v6 text;  
  v7 text;  
  v8 text;  
  v9 text;  
  v10 text;  
  v11 text;  
  v12 text;  
  v13 text;  
  r record;  
begin  
  GET DIAGNOSTICS v1 = ROW_COUNT,  
                  v2 = RESULT_OID,  
                  v3 = PG_CONTEXT;  
  RAISE NOTICE 'ROW_COUNT:%, RESULT_OID:%, PG_CONTEXT:%', v1,v2,v3;  
  
if TG_EVENT='ddl_command_end' then  
    FOR r IN SELECT * FROM pg_event_trigger_ddl_commands() LOOP  
        RAISE NOTICE 'classid:%, objid:%, objsubid:%, command_tag:%, object_type:%, schema_name:%, object_identity:%, in_extension:%, command:%',   
  r.classid, r.objid, r.objsubid, r.command_tag, r.object_type, r.schema_name, r.object_identity, r.in_extension, r.command;  
    END LOOP;  
end if;  
  
if TG_EVENT='sql_drop' then  
    FOR r IN SELECT * FROM pg_event_trigger_dropped_objects() LOOP  
        RAISE NOTICE 'classid:%, objid:%, objsubid:%, original:%, normal:%, is_temporary:%, object_type:%, schema_name:%, object_name:%, object_identity:%, address_names:%, address_args:%',   
  r.classid, r.objid, r.objsubid, r.original, r.normal, r.is_temporary, r.object_type, r.schema_name, r.object_name, r.object_identity, r.address_names, r.address_args;  
    END LOOP;  
end if;  
  
if TG_EVENT='table_rewrite' then  
    RAISE NOTICE 'rewriting table % for reason %',  
                pg_event_trigger_table_rewrite_oid()::regclass,  
                pg_event_trigger_table_rewrite_reason();  
end if;  
  
  raise exception 'error';  
  
  exception when others then  
    select hstore(pg_stat_activity.*) into rec from pg_stat_activity where pid=pg_backend_pid();  -- 记录pg_stat_activity的内容  
    insert into aud_alter (ctx) values (rec);  
    raise notice '%', rec;  
      
    GET STACKED DIAGNOSTICS v4 = RETURNED_SQLSTATE,  
                            v5 = COLUMN_NAME,  
                            v6 = CONSTRAINT_NAME,  
                            v7 = PG_DATATYPE_NAME,  
                            v8 = MESSAGE_TEXT,  
                            v9 = TABLE_NAME,  
                            v10 = SCHEMA_NAME,  
                            v11 = PG_EXCEPTION_DETAIL,  
                            v12 = PG_EXCEPTION_HINT,  
                            v13 = PG_EXCEPTION_CONTEXT;  
  
    RAISE NOTICE 'RETURNED_SQLSTATE:%, COLUMN_NAME:%, CONSTRAINT_NAME:%, PG_DATATYPE_NAME:%, MESSAGE_TEXT:%, TABLE_NAME:%, SCHEMA_NAME:%, PG_EXCEPTION_DETAIL:%, PG_EXCEPTION_HINT:%, PG_EXCEPTION_CONTEXT:%',   
      v4,v5,v6,v7,v8::text,v9,v10,v11,v12,v13;  
    raise exception 'error';  -- 回滚
end;  
$function$;


create event trigger e1 on ddl_command_end  execute procedure ef_alter();  

create event trigger e2 on sql_drop  execute procedure ef_alter();  

create event trigger e3 on table_rewrite  execute procedure ef_alter();  

```

**Comment by maksm90** [comment]
Probably, I know how to fail backend silently. Thanks for your case I will certainly explore it.

**Comment by maksm90** [comment]
Hi @digoal ! This commit c00cfed6e56f528da456248ad4a231f7f828fa81 fixes improper handled crash. Thanks for your case.
